service: serverless-rest-api
frameworkVersion: '>=1.28.0'
custom:
  secrets: ${file(secrets.json)}
  tableName: "test"
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
functions:
  api: 
    handler: bin/main
    events:
      - http:
          path: /ping
          method: GET
          cors: true
  login:
    handler: functions/login.handler
    events:
      - http:
           path: login
           method: post
           cors: true
  register:
    handler: functions/register.handler
    events:
      - http:
           path: register
           method: post
           cors: true
package:
  patterns:
    - "!*/**"
    - bin/main